use num_enum::{IntoPrimitive, TryFromPrimitive};

use crate::pp::Trait;

#[repr(u16)]
#[derive(TryFromPrimitive, IntoPrimitive)]
#[allow(non_camel_case_types)]
#[allow(clippy::upper_case_acronyms)]
pub enum PiiSpecies {
    BULBASAUR = 1,
    IVYSAUR = 2,
    VENUSAUR = 3,
    CHARMANDER = 4,
    CHARMELEON = 5,
    CHARIZARD = 6,
    SQUIRTLE = 7,
    WARTORTLE = 8,
    BLASTOISE = 9,
    CATERPIE = 10,
    METAPOD = 11,
    BUTTERFREE = 12,
    WEEDLE = 13,
    KAKUNA = 14,
    BEEDRILL = 15,
    PIDGEY = 16,
    PIDGEOTTO = 17,
    PIDGEOT = 18,
    RATTATA = 19,
    RATICATE = 20,
    SPEAROW = 21,
    FEAROW = 22,
    EKANS = 23,
    ARBOK = 24,
    PIKACHU = 25,
    RAICHU = 26,
    SANDSHREW = 27,
    SANDSLASH = 28,
    NIDORAN_F = 29,
    NIDORINA = 30,
    NIDOQUEEN = 31,
    NIDORAN_M = 32,
    NIDORINO = 33,
    NIDOKING = 34,
    CLEFAIRY = 35,
    CLEFABLE = 36,
    VULPIX = 37,
    NINETALES = 38,
    JIGGLYPUFF = 39,
    WIGGLYTUFF = 40,
    ZUBAT = 41,
    GOLBAT = 42,
    ODDISH = 43,
    GLOOM = 44,
    VILEPLUME = 45,
    PARAS = 46,
    PARASECT = 47,
    VENONAT = 48,
    VENOMOTH = 49,
    DIGLETT = 50,
    DUGTRIO = 51,
    MEOWTH = 52,
    PERSIAN = 53,
    PSYDUCK = 54,
    GOLDUCK = 55,
    MANKEY = 56,
    PRIMEAPE = 57,
    GROWLITHE = 58,
    ARCANINE = 59,
    POLIWAG = 60,
    POLIWHIRL = 61,
    POLIWRATH = 62,
    ABRA = 63,
    KADABRA = 64,
    ALAKAZAM = 65,
    MACHOP = 66,
    MACHOKE = 67,
    MACHAMP = 68,
    BELLSPROUT = 69,
    WEEPINBELL = 70,
    VICTREEBEL = 71,
    TENTACOOL = 72,
    TENTACRUEL = 73,
    GEODUDE = 74,
    GRAVELER = 75,
    GOLEM = 76,
    PONYTA = 77,
    RAPIDASH = 78,
    SLOWPOKE = 79,
    SLOWBRO = 80,
    MAGNEMITE = 81,
    MAGNETON = 82,
    FARFETCH_D = 83,
    DODUO = 84,
    DODRIO = 85,
    SEEL = 86,
    DEWGONG = 87,
    GRIMER = 88,
    MUK = 89,
    SHELLDER = 90,
    CLOYSTER = 91,
    GASTLY = 92,
    HAUNTER = 93,
    GENGAR = 94,
    ONIX = 95,
    DROWZEE = 96,
    HYPNO = 97,
    KRABBY = 98,
    KINGLER = 99,
    VOLTORB = 100,
    ELECTRODE = 101,
    EXEGGCUTE = 102,
    EXEGGUTOR = 103,
    CUBONE = 104,
    MAROWAK = 105,
    HITMONLEE = 106,
    HITMONCHAN = 107,
    LICKITUNG = 108,
    KOFFING = 109,
    WEEZING = 110,
    RHYHORN = 111,
    RHYDON = 112,
    CHANSEY = 113,
    TANGELA = 114,
    KANGASKHAN = 115,
    HORSEA = 116,
    SEADRA = 117,
    GOLDEEN = 118,
    SEAKING = 119,
    STARYU = 120,
    STARMIE = 121,
    MR_MIME = 122,
    SCYTHER = 123,
    JYNX = 124,
    ELECTABUZZ = 125,
    MAGMAR = 126,
    PINSIR = 127,
    TAUROS = 128,
    MAGIKARP = 129,
    GYARADOS = 130,
    LAPRAS = 131,
    DITTO = 132,
    EEVEE = 133,
    VAPOREON = 134,
    JOLTEON = 135,
    FLAREON = 136,
    PORYGON = 137,
    OMANYTE = 138,
    OMASTAR = 139,
    KABUTO = 140,
    KABUTOPS = 141,
    AERODACTYL = 142,
    SNORLAX = 143,
    ARTICUNO = 144,
    ZAPDOS = 145,
    MOLTRES = 146,
    DRATINI = 147,
    DRAGONAIR = 148,
    DRAGONITE = 149,
    MEWTWO = 150,
    MEW = 151,
    CHIKORITA = 152,
    BAYLEEF = 153,
    MEGANIUM = 154,
    CYNDAQUIL = 155,
    QUILAVA = 156,
    TYPHLOSION = 157,
    TOTODILE = 158,
    CROCONAW = 159,
    FERALIGATR = 160,
    SENTRET = 161,
    FURRET = 162,
    HOOTHOOT = 163,
    NOCTOWL = 164,
    LEDYBA = 165,
    LEDIAN = 166,
    SPINARAK = 167,
    ARIADOS = 168,
    CROBAT = 169,
    CHINCHOU = 170,
    LANTURN = 171,
    PICHU = 172,
    CLEFFA = 173,
    IGGLYBUFF = 174,
    TOGEPI = 175,
    TOGETIC = 176,
    NATU = 177,
    XATU = 178,
    MAREEP = 179,
    FLAAFFY = 180,
    AMPHAROS = 181,
    BELLOSSOM = 182,
    MARILL = 183,
    AZUMARILL = 184,
    SUDOWOODO = 185,
    POLITOED = 186,
    HOPPIP = 187,
    SKIPLOOM = 188,
    JUMPLUFF = 189,
    AIPOM = 190,
    SUNKERN = 191,
    SUNFLORA = 192,
    YANMA = 193,
    WOOPER = 194,
    QUAGSIRE = 195,
    ESPEON = 196,
    UMBREON = 197,
    MURKROW = 198,
    SLOWKING = 199,
    MISDREAVUS = 200,
    UNOWN = 201,
    WOBBUFFET = 202,
    GIRAFARIG = 203,
    PINECO = 204,
    FORRETRESS = 205,
    DUNSPARCE = 206,
    GLIGAR = 207,
    STEELIX = 208,
    SNUBBULL = 209,
    GRANBULL = 210,
    QWILFISH = 211,
    SCIZOR = 212,
    SHUCKLE = 213,
    HERACROSS = 214,
    SNEASEL = 215,
    TEDDIURSA = 216,
    URSARING = 217,
    SLUGMA = 218,
    MAGCARGO = 219,
    SWINUB = 220,
    PILOSWINE = 221,
    CORSOLA = 222,
    REMORAID = 223,
    OCTILLERY = 224,
    DELIBIRD = 225,
    MANTINE = 226,
    SKARMORY = 227,
    HOUNDOUR = 228,
    HOUNDOOM = 229,
    KINGDRA = 230,
    PHANPY = 231,
    DONPHAN = 232,
    PORYGON2 = 233,
    STANTLER = 234,
    SMEARGLE = 235,
    TYROGUE = 236,
    HITMONTOP = 237,
    SMOOCHUM = 238,
    ELEKID = 239,
    MAGBY = 240,
    MILTANK = 241,
    BLISSEY = 242,
    RAIKOU = 243,
    ENTEI = 244,
    SUICUNE = 245,
    LARVITAR = 246,
    PUPITAR = 247,
    TYRANITAR = 248,
    LUGIA = 249,
    HO_OH = 250,
    CELEBI = 251,
    TREECKO = 252,
    GROVYLE = 253,
    SCEPTILE = 254,
    TORCHIC = 255,
    COMBUSKEN = 256,
    BLAZIKEN = 257,
    MUDKIP = 258,
    MARSHTOMP = 259,
    SWAMPERT = 260,
    POOCHYENA = 261,
    MIGHTYENA = 262,
    ZIGZAGOON = 263,
    LINOONE = 264,
    WURMPLE = 265,
    SILCOON = 266,
    BEAUTIFLY = 267,
    CASCOON = 268,
    DUSTOX = 269,
    LOTAD = 270,
    LOMBRE = 271,
    LUDICOLO = 272,
    SEEDOT = 273,
    NUZLEAF = 274,
    SHIFTRY = 275,
    TAILLOW = 276,
    SWELLOW = 277,
    WINGULL = 278,
    PELIPPER = 279,
    RALTS = 280,
    KIRLIA = 281,
    GARDEVOIR = 282,
    SURSKIT = 283,
    MASQUERAIN = 284,
    SHROOMISH = 285,
    BRELOOM = 286,
    SLAKOTH = 287,
    VIGOROTH = 288,
    SLAKING = 289,
    NINCADA = 290,
    NINJASK = 291,
    SHEDINJA = 292,
    WHISMUR = 293,
    LOUDRED = 294,
    EXPLOUD = 295,
    MAKUHITA = 296,
    HARIYAMA = 297,
    AZURILL = 298,
    NOSEPASS = 299,
    SKITTY = 300,
    DELCATTY = 301,
    SABLEYE = 302,
    MAWILE = 303,
    ARON = 304,
    LAIRON = 305,
    AGGRON = 306,
    MEDITITE = 307,
    MEDICHAM = 308,
    ELECTRIKE = 309,
    MANECTRIC = 310,
    PLUSLE = 311,
    MINUN = 312,
    VOLBEAT = 313,
    ILLUMISE = 314,
    ROSELIA = 315,
    GULPIN = 316,
    SWALOT = 317,
    CARVANHA = 318,
    SHARPEDO = 319,
    WAILMER = 320,
    WAILORD = 321,
    NUMEL = 322,
    CAMERUPT = 323,
    TORKOAL = 324,
    SPOINK = 325,
    GRUMPIG = 326,
    SPINDA = 327,
    TRAPINCH = 328,
    VIBRAVA = 329,
    FLYGON = 330,
    CACNEA = 331,
    CACTURNE = 332,
    SWABLU = 333,
    ALTARIA = 334,
    ZANGOOSE = 335,
    SEVIPER = 336,
    LUNATONE = 337,
    SOLROCK = 338,
    BARBOACH = 339,
    WHISCASH = 340,
    CORPHISH = 341,
    CRAWDAUNT = 342,
    BALTOY = 343,
    CLAYDOL = 344,
    LILEEP = 345,
    CRADILY = 346,
    ANORITH = 347,
    ARMALDO = 348,
    FEEBAS = 349,
    MILOTIC = 350,
    CASTFORM = 351,
    KECLEON = 352,
    SHUPPET = 353,
    BANETTE = 354,
    DUSKULL = 355,
    DUSCLOPS = 356,
    TROPIUS = 357,
    CHIMECHO = 358,
    ABSOL = 359,
    WYNAUT = 360,
    SNORUNT = 361,
    GLALIE = 362,
    SPHEAL = 363,
    SEALEO = 364,
    WALREIN = 365,
    CLAMPERL = 366,
    HUNTAIL = 367,
    GOREBYSS = 368,
    RELICANTH = 369,
    LUVDISC = 370,
    BAGON = 371,
    SHELGON = 372,
    SALAMENCE = 373,
    BELDUM = 374,
    METANG = 375,
    METAGROSS = 376,
    REGIROCK = 377,
    REGICE = 378,
    REGISTEEL = 379,
    LATIAS = 380,
    LATIOS = 381,
    KYOGRE = 382,
    GROUDON = 383,
    RAYQUAZA = 384,
    JIRACHI = 385,
    DEOXYS = 386,
    TURTWIG = 387,
    GROTLE = 388,
    TORTERRA = 389,
    CHIMCHAR = 390,
    MONFERNO = 391,
    INFERNAPE = 392,
    PIPLUP = 393,
    PRINPLUP = 394,
    EMPOLEON = 395,
    STARLY = 396,
    STARAVIA = 397,
    STARAPTOR = 398,
    BIDOOF = 399,
    BIBAREL = 400,
    KRICKETOT = 401,
    KRICKETUNE = 402,
    SHINX = 403,
    LUXIO = 404,
    LUXRAY = 405,
    BUDEW = 406,
    ROSERADE = 407,
    CRANIDOS = 408,
    RAMPARDOS = 409,
    SHIELDON = 410,
    BASTIODON = 411,
    BURMY = 412,
    WORMADAM = 413,
    MOTHIM = 414,
    COMBEE = 415,
    VESPIQUEN = 416,
    PACHIRISU = 417,
    BUIZEL = 418,
    FLOATZEL = 419,
    CHERUBI = 420,
    CHERRIM = 421,
    SHELLOS = 422,
    GASTRODON = 423,
    AMBIPOM = 424,
    DRIFLOON = 425,
    DRIFBLIM = 426,
    BUNEARY = 427,
    LOPUNNY = 428,
    MISMAGIUS = 429,
    HONCHKROW = 430,
    GLAMEOW = 431,
    PURUGLY = 432,
    CHINGLING = 433,
    STUNKY = 434,
    SKUNTANK = 435,
    BRONZOR = 436,
    BRONZONG = 437,
    BONSLY = 438,
    MIME_JR = 439,
    HAPPINY = 440,
    CHATOT = 441,
    SPIRITOMB = 442,
    GIBLE = 443,
    GABITE = 444,
    GARCHOMP = 445,
    MUNCHLAX = 446,
    RIOLU = 447,
    LUCARIO = 448,
    HIPPOPOTAS = 449,
    HIPPOWDON = 450,
    SKORUPI = 451,
    DRAPION = 452,
    CROAGUNK = 453,
    TOXICROAK = 454,
    CARNIVINE = 455,
    FINNEON = 456,
    LUMINEON = 457,
    MANTYKE = 458,
    SNOVER = 459,
    ABOMASNOW = 460,
    WEAVILE = 461,
    MAGNEZONE = 462,
    LICKILICKY = 463,
    RHYPERIOR = 464,
    TANGROWTH = 465,
    ELECTIVIRE = 466,
    MAGMORTAR = 467,
    TOGEKISS = 468,
    YANMEGA = 469,
    LEAFEON = 470,
    GLACEON = 471,
    GLISCOR = 472,
    MAMOSWINE = 473,
    PORYGON_Z = 474,
    GALLADE = 475,
    PROBOPASS = 476,
    DUSKNOIR = 477,
    FROSLASS = 478,
    ROTOM = 479,
    UXIE = 480,
    MESPRIT = 481,
    AZELF = 482,
    DIALGA = 483,
    PALKIA = 484,
    HEATRAN = 485,
    REGIGIGAS = 486,
    GIRATINA = 487,
    CRESSELIA = 488,
    PHIONE = 489,
    MANAPHY = 490,
    DARKRAI = 491,
    SHAYMIN = 492,
    ARCEUS = 493,
    EGG = 494,
    BAD_EGG = 495,
    NIDORAN = 496,
}

/// All possible Pokémon. Note that some Pokémon were scrapped from the game and require the 
/// [Weekend Edition Mod](https://projectpokemon.org/home/files/file/4256-pokemon-rumble-weekend-edition/)
/// to work properly.
pub const POKEMON_NAMES: [&str; 496] = [
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran♀",
    "Nidorina",
    "Nidoqueen",
    "Nidoran♂",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch’d",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Wormadam",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Shellos",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
    "Egg",
    "Bad Egg",
    "NIDORAN",
];

pub const UNOWN_FORMS: [(&str, &str); 28] = [
    ("Unown A", "201"),
    ("Unown B", "201-b"),
    ("Unown C", "201-c"),
    ("Unown D", "201-d"),
    ("Unown E", "201-e"),
    ("Unown F", "201-f"),
    ("Unown G", "201-g"),
    ("Unown H", "201-h"),
    ("Unown I", "201-i"),
    ("Unown J", "201-j"),
    ("Unown K", "201-k"),
    ("Unown L", "201-l"),
    ("Unown M", "201-m"),
    ("Unown N", "201-n"),
    ("Unown O", "201-o"),
    ("Unown P", "201-p"),
    ("Unown Q", "201-q"),
    ("Unown R", "201-r"),
    ("Unown S", "201-s"),
    ("Unown T", "201-t"),
    ("Unown U", "201-u"),
    ("Unown V", "201-v"),
    ("Unown W", "201-w"),
    ("Unown X", "201-x"),
    ("Unown Y", "201-y"),
    ("Unown Z", "201-z"),
    ("Unown !", "201-exclamation"),
    ("Unown ?", "201-question"),
];

pub const CASTFORM_FORMS: [(&str, &str); 4] = [
    ("Castform", "201"),
    ("Castform (Sunny form)", "10013"),
    ("Castform (Rainy form)", "10014"),
    ("Castform (Snowy form)", "10015"),
];

pub const DEOXYS_FORMS: [(&str, &str); 4] = [
    ("Deoxys (Normal form)", "386"),
    ("Deoxys (Attack form)", "10001"),
    ("Deoxys (Defence form)", "10002"),
    ("Deoxys (Speed form)", "10003"),
];

pub const BURMY_FORMS: [(&str, &str); 3] = [
    ("Burmy (Plant Cloak)", "412"),
    ("Burmy (Sandy Cloak)", "412-sandy"),
    ("Burmy (Trash Cloak)", "412-trash"),
];

pub const WORMADAM_FORMS: [(&str, &str); 3] = [
    ("Wormadam (Plant Cloak)", "413"),
    ("Wormadam (Sandy Cloak)", "10004"),
    ("Wormadam (Trash Cloak)", "10005"),
];

pub const CHERRIM_FORMS: [(&str, &str); 2] = [
    ("Overcast Cherrim", "421"),
    ("Sunshine Cherrim", "421-sunshine"),
];

pub const SHELLOS_FORMS: [(&str, &str); 2] =
    [("West Shellos", "422"), ("East Shellos", "422-east")];

pub const GASTRODON_FORMS: [(&str, &str); 2] =
    [("West Gastrodon", "423"), ("East Gastrodon", "423-east")];

pub const ROTOM_FORMS: [(&str, &str); 6] = [
    ("Rotom", "479"),
    ("Heat Rotom", "10008"),
    ("Wash Rotom", "10009"),
    ("Frost Rotom", "10010"),
    ("Fan Rotom", "10011"),
    ("Mow Rotom", "10012"),
];

pub const GIRATINA_FORMS: [(&str, &str); 2] = [
    ("Giratina (Altered Forme)", "487"),
    ("Giratina (Origin Forme)", "10007"),
];

pub const SHAYMIN_FORMS: [(&str, &str); 2] = [
    ("Shaymin (Land Forme)", "492"),
    ("Shaymin (Sky Forme)", "10006"),
];

pub const ARCEUS_FORMS: [(&str, &str); 19] = [
    ("Normal Arceus", "pokemon/493"),
    ("Bug Arceus", "493-bug"),
    ("Dark Arceus", "493-dark"),
    ("Dragon Arceus", "493-dragon"),
    ("Electric Arceus", "493-electric"),
    ("Fighting Arceus", "493-fighting"),
    ("Fire Arceus", "493-fire"),
    ("Flying Arceus", "493-flying"),
    ("Ghost Arceus", "493-ghost"),
    ("Grass Arceus", "493-grass"),
    ("Ground Arceus", "493-ground"),
    ("Ice Arceus", "493-ice"),
    ("Poison Arceus", "493-poison"),
    ("Psychic Arceus", "493-psychic"),
    ("Rock Arceus", "493-rock"),
    ("Steel Arceus", "493-steel"),
    ("Water Arceus", "493-water"),
    ("??? Arceus", "493-unknown"),
    ("Fairy Arceus", "493-fairy"),
];

/// All possible moves. Data comes from the english localization in the game's files
pub const MOVES: [&str; 549] = [
    "-----",
    "B No Type Blast",
    "B No Type Restart",
    "B No Type Dash",
    "B PoisonPowder",
    "B Water Gun",
    "B Bonemerang",
    "B Fury Swipes",
    "B Poison Sting",
    "B Ember",
    "B Thunderbolt",
    "B Powder Snow",
    "B ThunderPunch",
    "B Gust",
    "B Rock Blast",
    "B Flamethrower",
    "B Water Pulse",
    "B Shadow Ball",
    "B AncientPower",
    "B Ice Beam",
    "B Yawn",
    "B Hydro Pump",
    "B Thunder",
    "B Dragon Rage",
    "B Blizzard",
    "B Heat Wave",
    "B Razor Leaf",
    "B Bubble",
    "B Psywave",
    "B Poison Jab",
    "B Mach Punch",
    "B Attack Order",
    "B Sand Tomb",
    "B Confusion",
    "B Wing Attack",
    "B Ice Shard",
    "B Thunder Fang",
    "B Giga Drain",
    "B Whirlpool",
    "B Shadow Punch",
    "B Power Whip",
    "B Close Combat",
    "B Psycho Cut",
    "B Giga Impact",
    "B Ominous Wind",
    "B Aura Sphere",
    "B Dragon Claw",
    "B Magma Storm",
    "M2 Psycho Cut 1",
    "M2 Psychic 1",
    "M2 Psycho Cut 2",
    "M2 Psychic 2",
    "M2 Psycho Cut 3",
    "M2 Psychic 3",
    "Ice Ball",
    "Aqua Jet",
    "Aqua Tail",
    "Spacial Rend",
    "Vital Throw",
    "Dig",
    "Cut",
    "Rage",
    "Rock Throw",
    "Weather Ball",
    "Air Cutter",
    "Aeroblast",
    "Pursuit",
    "DoubleSlap 5th",
    "DoubleSlap 4th",
    "DoubleSlap",
    "DoubleSlap 2nd",
    "DoubleSlap Finish",
    "Aurora Beam",
    "Octazooka",
    "Strength",
    "Shadow Sneak",
    "Gust",
    "Razor Wind",
    "Facade",
    "Facade L",
    "Karate Chop",
    "Brick Break",
    "Rock Wrecker",
    "Giga Impact",
    "Slash",
    "Crabhammer",
    "Cross Chop",
    "Attack Order",
    "Rapid Spin",
    "Ice Shard",
    "Rollout",
    "Psycho Cut",
    "Psychic",
    "Uproar 2",
    "Uproar",
    "Uproar 4",
    "Uproar 5",
    "Water Spout",
    "Brine",
    "X-Scissor",
    "Earthquake",
    "Shadow Claw",
    "Shadow Claw L",
    "Shadow Force",
    "Shadow Punch",
    "Thunderbolt",
    "Vacuum Wave",
    "ExtremeSpeed",
    "Sky Uppercut",
    "Stone Edge",
    "Swift",
    "SolarBeam",
    "Fly",
    "Tackle",
    "Dive",
    "Muddy Water",
    "Slam",
    "Seed Bomb",
    "Bullet Seed",
    "Bullet Seed 4th",
    "Bullet Seed 3rd",
    "Bullet Seed 2nd",
    "Bullet Seed 1st",
    "Double Hit",
    "Double Hit Finish",
    "Egg Bomb",
    "Faint Attack",
    "Barrage",
    "Barrage 4th",
    "Barrage 3rd",
    "Barrage 2nd",
    "Barrage 1st",
    "Night Slash",
    "Peck",
    "Peck L",
    "Arm Thrust",
    "Arm Thrust 4th",
    "Arm Thrust 3rd",
    "Arm Thrust 2nd",
    "Arm Thrust Finish",
    "Horn Attack",
    "Wing Attack",
    "Aerial Ace",
    "Icicle Spear",
    "Icicle Spear 4th",
    "Icicle Spear 3rd",
    "Icicle Spear 2nd",
    "Icicle Spear 1st",
    "Vine Whip",
    "Test",
    "Shock Wave",
    "Quick Attack",
    "Roar of Time",
    "Spike Cannon",
    "Spike Cannon 4th",
    "Spike Cannon 3rd",
    "Spike Cannon 2nd",
    "Spike Cannon 1st",
    "Dragon Claw",
    "Dragon Claw L",
    "Triple Kick",
    "Triple Kick 2",
    "Triple Kick Finish",
    "Drill Peck",
    "Surf",
    "Double Kick",
    "Double Kick 2",
    "Frenzy Plant",
    "Hydro Cannon",
    "Hydro Pump",
    "Hyper Voice",
    "Hyper Beam",
    "ViceGrip",
    "Pound",
    "Razor Leaf",
    "Aura Sphere",
    "Bullet Punch",
    "Power Whip",
    "Power Gem",
    "Scratch",
    "Sucker Punch",
    "Blast Burn",
    "Eruption",
    "Bone Rush 5th",
    "Bone Rush 4th",
    "Bone Rush",
    "Bone Rush 2nd",
    "Bone Rush Finish",
    "Bonemerang",
    "Bonemerang 2",
    "Magnet Bomb",
    "Magical Leaf",
    "Mach Punch",
    "Mach Punch L",
    "Pin Missile 5th",
    "Pin Missile 4th",
    "Pin Missile",
    "Pin Missile 2nd",
    "Pin Missile 1st",
    "Water Gun",
    "Fury Attack 5th",
    "Fury Attack 4th",
    "Fury Attack",
    "Fury Attack 2nd",
    "Fury Attack Finish",
    "Fury Swipes",
    "Fury Swipes 4th",
    "Fury Swipes 3rd",
    "Fury Swipes 2nd",
    "Fury Swipes Finish",
    "False Swipe",
    "Mega Kick",
    "Mega Punch",
    "Megahorn",
    "Wake-Up Slap",
    "Leaf Blade",
    "Dragon Pulse",
    "Fury Cutter",
    "Fury Cutter 2",
    "Comet Punch 5th",
    "Comet Punch",
    "Comet Punch 3rd",
    "Comet Punch 2nd",
    "Comet Punch Finish",
    "Rock Blast",
    "Super Fang",
    "Punishment",
    "Reversal",
    "Grass Knot",
    "Low Kick",
    "Psywave",
    "Flail",
    "Wring Out",
    "SonicBoom",
    "Seismic Toss",
    "Night Shade",
    "Crush Grip",
    "Present",
    "Magnitude",
    "Hidden Power (Normal)",
    "Hidden Power (Fighting)",
    "Hidden Power (Flying)",
    "Hidden Power (Poison)",
    "Hidden Power (Ground)",
    "Hidden Power (Rock)",
    "Hidden Power (Bug)",
    "Hidden Power (Ghost)",
    "Hidden Power (Steel)",
    "Hidden Power (?)",
    "Hidden Power (Fire)",
    "Hidden Power (Water)",
    "Hidden Power (Grass)",
    "Hidden Power (Electric)",
    "Hidden Power (Psychic)",
    "Hidden Power (Ice)",
    "Hidden Power (Dragon)",
    "Hidden Power (Dark)",
    "Dragon Rage",
    "Cross Poison",
    "Smog",
    "Gunk Shot",
    "Twineedle",
    "Twineedle Finish",
    "Poison Gas",
    "Poison Jab",
    "Poison Jab L",
    "PoisonPowder",
    "Poison Sting",
    "Sludge",
    "Sludge Bomb",
    "Poison Tail",
    "Toxic",
    "Poison Fang",
    "Will-O-Wisp",
    "Flame Wheel",
    "Flamethrower",
    "Sacred Fire",
    "Fire Blast",
    "Heat Wave",
    "Ember",
    "Blaze Kick",
    "Lava Plume",
    "Fire Punch",
    "Iron Head",
    "Dark Pulse",
    "Rock Slide",
    "Air Slash",
    "Astonish",
    "Bite",
    "Sky Attack",
    "Zen Headbutt",
    "Extrasensory",
    "Headbutt",
    "Waterfall",
    "Twister",
    "Dragon Rush",
    "Needle Arm",
    "Fake Out",
    "Hyper Fang",
    "Stomp",
    "Bone Club",
    "Rolling Kick",
    "Bubble",
    "Constrict",
    "Rock Tomb",
    "Icy Wind",
    "BubbleBeam",
    "Mud Shot",
    "Iron Tail",
    "Rock Smash",
    "Energy Ball",
    "Crunch",
    "Focus Blast",
    "Shadow Ball",
    "Earth Power",
    "Crush Claw",
    "Crush Claw L",
    "Bug Buzz",
    "Acid",
    "Flash Cannon",
    "Luster Purge",
    "Mist Ball",
    "Double-Edge",
    "Take Down",
    "Jump Kick",
    "Hi Jump Kick",
    "Flare Blitz",
    "Brave Bird",
    "Head Smash",
    "Skull Bash",
    "Powder Snow",
    "Blizzard",
    "Ice Punch",
    "Ice Beam",
    "Thunder",
    "ThunderPunch",
    "Lick",
    "Stun Spore",
    "Spark",
    "ThunderShock",
    "Thunder Wave",
    "Zap Cannon",
    "Bounce",
    "Body Slam",
    "Force Palm",
    "Discharge",
    "Volt Tackle",
    "DragonBreath",
    "Yawn",
    "Lovely Kiss",
    "Sing",
    "Spore",
    "GrassWhistle",
    "Hypnosis",
    "Sleep Powder",
    "Whirlpool 2",
    "Whirlpool",
    "Whirlpool 4",
    "Whirlpool 5",
    "Clamp 2",
    "Clamp",
    "Clamp 4",
    "Clamp 5",
    "Bind 2",
    "Bind",
    "Bind 4",
    "Bind 5",
    "Sand Tomb 2",
    "Sand Tomb",
    "Sand Tomb 4",
    "Sand Tomb 5",
    "Fire Spin 2",
    "Fire Spin",
    "Fire Spin 4",
    "Fire Spin 5",
    "Wrap 2",
    "Wrap",
    "Wrap 4",
    "Wrap 5",
    "Magma Storm 2",
    "Magma Storm",
    "Magma Storm 4",
    "Magma Storm 5",
    "Confuse Ray",
    "Psybeam",
    "Signal Beam",
    "Supersonic",
    "Sweet Kiss",
    "Confusion",
    "DynamicPunch",
    "Dizzy Punch",
    "Teeter Dance",
    "Water Pulse",
    "Rock Climb",
    "Ice Fang",
    "Thunder Fang",
    "Fire Fang",
    "Swagger",
    "Flatter",
    "Thrash",
    "Thrash 3",
    "Outrage",
    "Outrage 3",
    "Petal Dance",
    "Petal Dance 3",
    "Selfdestruct",
    "Explosion",
    "Hammer Arm",
    "Giga Drain",
    "Leech Life",
    "Absorb",
    "Drain Punch",
    "Mega Drain",
    "Meteor Mash",
    "Charge Beam",
    "Metal Claw",
    "Metal Claw L",
    "Overheat",
    "Psycho Boost",
    "Leaf Storm",
    "Draco Meteor",
    "Superpower",
    "Ingrain",
    "Wood Hammer",
    "Submission",
    "Ominous Wind",
    "Silver Wind",
    "AncientPower",
    "Steel Wing",
    "Close Combat",
    "Close Combat L",
    "Tri Attack",
    "SmellingSalt",
    "Harden",
    "Mud-Slap",
    "Teleport",
    "Revenge",
    "Avalanche",
    "Splash",
    "Growl",
    "Bide",
    "Screech",
    "Mirror Shot",
    "Mud Bomb",
    "Withdraw",
    "Cosmic Power",
    "Iron Defense",
    "Acid Armor",
    "Amnesia",
    "Barrier",
    "Defend Order",
    "Defense Curl",
    "Charge",
    "Payback",
    "SmokeScreen",
    "Sand-Attack",
    "Kinesis",
    "Flash",
    "Gravity",
    "Charm",
    "FeatherDance",
    "Counter",
    "Mirror Coat",
    "Metal Burst",
    "Fake Tears",
    "Metal Sound",
    "Tail Whip",
    "Leer",
    "Aqua Ring",
    "Aromatherapy",
    "Heal Bell",
    "Refresh",
    "Safeguard",
    "Glare",
    "Torment",
    "Disable",
    "String Shot",
    "Scary Face",
    "Cotton Spore",
    "Tailwind",
    "Agility",
    "Rock Polish",
    "Tickle",
    "Heal Order",
    "Recover",
    "Softboiled",
    "Slack Off",
    "Wish",
    "Roost",
    "Milk Drink",
    "Rest",
    "Leech Seed",
    "Sharpen",
    "Growth",
    "Swords Dance",
    "Howl",
    "Tail Glow",
    "Meditate",
    "Nasty Plot",
    "Belly Drum",
    "Bulk Up",
    "Calm Mind",
    "Dragon Dance",
    "Endeavor",
    "Focus Energy",
    "Focus Punch",
    "Pain Split",
    "Light Screen",
    "Reflect",
    "Spider Web",
    "Mean Look",
    "Block",
    "Haze",
    "Mist",
    "Mind Reader",
    "Lock-On",
    "Endure",
    "Protect",
    "Detect",
    "Fissure",
    "Sheer Cold",
    "Horn Drill",
    "Guillotine",
    "Perish Song",
    "Assurance",
    "Minimize",
    "Acupressure",
    "Helping Hand",
    "Toxic Spikes",
    "Spikes",
    "Thief",
    "Pay Day",
    "Knock Off",
    "Covet",
    "Bug Bite",
    "U-turn",
    "Whirlwind",
    "Roar",
    "Doom Desire",
    "Future Sight",
    "Secret Power",
    "Magic Coat",
    "Destiny Bond",
    "Morning Sun",
    "Synthesis",
    "Moonlight",
    "Seed Flare",
    "Dark Void",
    "Struggle",
];

/// All possible traits. Data comes from the english localization in the game's files
pub const TRAITS: [Trait; 43] = [
    Trait {
        name: "Speedy",
        description: "It can move around fast.",
    },
    Trait {
        name: "Snappy",
        description: "It can use its moves quickly.",
    },
    Trait {
        name: "Punchy",
        description: "It has higher Attack.",
    },
    Trait {
        name: "Brawny",
        description: "It has higher HP.",
    },
    Trait {
        name: "Hardy",
        description: "It has higher Defense.",
    },
    Trait {
        name: "Lucky",
        description: "Foe drops more money.",
    },
    Trait {
        name: "Healthy",
        description: "It restores HP slowly.",
    },
    Trait {
        name: "Rally",
        description: "Other players' Pokémon get\n stronger during Multiplayer mode.",
    },
    Trait {
        name: "Scrappy",
        description: "It has a higher critical-hit rate.",
    },
    Trait {
        name: "Gutsy",
        description: "It has a very high critical-hit rate.",
    },
    Trait {
        name: "Perky",
        description: "It recovers quickly from a\n Status Change.",
    },
    Trait {
        name: "Steady",
        description: "It is not affected by any\n Status Changes.",
    },
    Trait {
        name: "Techie",
        description: "Moves with fewer ★s\n become stronger.",
    },
    Trait {
        name: "Feisty",
        description: "Its moves sweep foes to a further\n distance.",
    },
    Trait {
        name: "Mighty",
        description: "It does not get swept away much.",
    },
    Trait {
        name: "Normal Guard",
        description: "Normal-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Fight Guard",
        description: "Fighting-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Flying Guard",
        description: "Flying-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Poison Guard",
        description: "Poison-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Ground Guard",
        description: "Ground-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Rock Guard",
        description: "Rock-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Bug Guard",
        description: "Bug-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Ghost Guard",
        description: "Ghost-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Steel Guard",
        description: "Steel-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Dummy",
        description: "Explanation to dummy",
    },
    Trait {
        name: "Fire Guard",
        description: "Fire-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Water Guard",
        description: "Water-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Grass Guard",
        description: "Grass-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Electric Guard",
        description: "Electric-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Psychic Guard",
        description: "Psychic-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Ice Guard",
        description: "Ice-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Dragon Guard",
        description: "Dragon-type moves do not damage\n it very much.",
    },
    Trait {
        name: "Dark Guard",
        description: "Dark-type moves do not damage\n it very much.",
    },
    Trait {
        name: "????",
        description: "????",
    },
    Trait {
        name: "????",
        description: "????",
    },
    Trait {
        name: "?????",
        description: "????",
    },
    Trait {
        name: "?????",
        description: "????",
    },
    Trait {
        name: "?????",
        description: "????",
    },
    Trait {
        name: "?????",
        description: "????",
    },
    Trait {
        name: "?????",
        description: "????",
    },
    Trait {
        name: "?????",
        description: "????",
    },
    Trait {
        name: "????",
        description: "????",
    },
    Trait {
        name: "????",
        description: "????",
    },
];
